### ISSUE TITLE
[main] ERROR de.karstenbecker.daikin.Daikin - Failed to collect data

### ISSUE THREAD

**Issue by mihsu81** [SmartHomeIntegrationTech/MQTTServices-Daikin#11]
Hi @KarstenB,

I am getting the below error when trying to run the jar. Some of the values are published to MQTT, but not all.
I'm attaching also [PollingSettings.json](https://github.com/SmartHomeIntegrationTech/MQTTServices-Daikin/files/13857765/PollingSettings.json).

```
java -jar daikin.jar -c PollingSettings.json -p
[main] INFO org.eclipse.jetty.util.log - Logging initialized @197ms to org.eclipse.jetty.util.log.Slf4jLog
ian. 08, 2024 10:22:08 A.M. io.github.dschanoeh.homie_java.Homie lambda$new$0
INFO: --> init
ian. 08, 2024 10:22:09 A.M. io.github.dschanoeh.homie_java.Homie lambda$new$0
INFO: --> ready
[main] ERROR de.karstenbecker.daikin.Daikin - Failed to collect data
java.lang.UnsupportedOperationException: Trying to send an enum value which isn't included in the list of provided values
        at io.github.dschanoeh.homie_java.Property.send(Property.java:130)
        at de.karstenbecker.daikin.Daikin.pollItem(Daikin.java:618)
        at de.karstenbecker.daikin.Daikin.startPolling(Daikin.java:432)
        at de.karstenbecker.daikin.Daikin.main(Daikin.java:361)
``` 
![image](https://github.com/SmartHomeIntegrationTech/MQTTServices-Daikin/assets/40715497/080ea140-d670-4769-963b-b6bf0b7375a3)

**Comment by mihsu81** [comment]
And hourly the following warnings:
```
[main] WARN de.karstenbecker.daikin.Daikin - Checking DaikinProperty [path=1/Schedule/Active, name=SpaceHeating/Schedule/Active, id=1-schedule-active, value=null, settable=false, retained=true, unit=, format=, pollInterval=HOURLY, dataType=STRING]
[main] WARN de.karstenbecker.daikin.Daikin - Checking DaikinProperty [path=1/Schedule/Next, name=SpaceHeating/Schedule/Next, id=1-schedule-next, value=null, settable=false, retained=true, unit=, format=, pollInterval=HOURLY, dataType=STRING]
[main] WARN de.karstenbecker.daikin.Daikin - Checking DaikinProperty [path=1/Schedule/Active, name=SpaceHeating/Schedule/Active, id=1-schedule-active, value=null, settable=false, retained=true, unit=, format=, pollInterval=HOURLY, dataType=STRING]
[main] WARN de.karstenbecker.daikin.Daikin - Checking DaikinProperty [path=1/Schedule/Next, name=SpaceHeating/Schedule/Next, id=1-schedule-next, value=null, settable=false, retained=true, unit=, format=, pollInterval=HOURLY, dataType=STRING]
```
