### ISSUE TITLE
BRP069A78 support

### ISSUE THREAD

**Issue by FrAcTi0N** [SmartHomeIntegrationTech/MQTTServices-Daikin#9]
Hi, I am trying to discover my wlan adapter, but without any success. I use BRP069A78 instead of BRP069A62. Any hints, what can i try to discover it with all endpoints?
fra@Mareks-Air daikin % java -jar Daikin-0.0.5.jar -d             
[main] INFO org.eclipse.jetty.util.log - Logging initialized @56ms to org.eclipse.jetty.util.log.Slf4jLog

or 

java -jar Daikin-0.0.5.jar -w 192.168.0.71
[main] INFO org.eclipse.jetty.util.log - Logging initialized @124ms to org.eclipse.jetty.util.log.Slf4jLog
Scanning 192.168.0.71
java.util.concurrent.ExecutionException: org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at de.karstenbecker.daikin.WebsocketHelper.connect(WebsocketHelper.java:180)
	at de.karstenbecker.daikin.Daikin.discoverProperties(Daikin.java:113)
	at de.karstenbecker.daikin.Daikin.writeDiscoveredProperties(Daikin.java:637)
	at de.karstenbecker.daikin.Daikin.main(Daikin.java:344)
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:537)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:374)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1186)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1559)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:208)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:148)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.ArrayList.addAll(ArrayList.java:670)
	at de.karstenbecker.daikin.DaikinPollingSettings.<init>(DaikinPollingSettings.java:33)
	at de.karstenbecker.daikin.Daikin.writeDiscoveredProperties(Daikin.java:638)
	at de.karstenbecker.daikin.Daikin.main(Daikin.java:344)

thank You

**Comment by KarstenB** [comment]
Unfortunately I don't have a BRP069A78, but it appears to not like talking to the software. With a websocket. In order to understand whether I simply does not like the websocket protocol, or is a different protocol altogether, could you run this:
```
curl "http://192.168.0.71" \
     -d "{\"m2m:rqp\": {\"op\": 2,\"to\": \"/[0]/MNCSE-node/deviceInfo\",\"fr\": \"/OpenHab\",\"rqi\": \"ABCD\"}}"
```

**Comment by FrAcTi0N** [comment]
curl "http://192.168.0.71" \
     -d "{\"m2m:rqp\": {\"op\": 2,\"to\": \"/[0]/MNCSE-node/deviceInfo\",\"fr\": \"/OpenHab\",\"rqi\": \"ABCD\"}}"
File / not_found

**Comment by FrAcTi0N** [comment]
well, it looks like that it is not possible to connect locally with this adapter according to some research i did...

**Comment by KarstenB** [comment]
Yeah, the other implementations are all using the remote API. However the fact that you did get a proper http response makes me optimistic that there is a m2m endpoint running there. The difficulty will be figuring out where the endpoint is, and what it's protocol looks like. You might want to check if your phone app is doing local communication by doing a "man in the middle" inspection of the communication.

Here is a document that outlines how the M2m protocol is working over plain http: https://www.onem2m.org/images/files/deliverables/Release2A/TS-0009-HTTP_Protocol_Binding-v_2_13_1.pdf

One proposed URL is: myCSE/-/Cont1?atrl=ri+lbl+rr

So maybe `curl "http://192.168.0.71/[0]/MNCSE-node/deviceInfo" -d "<?xml version="1.0" encoding="UTF-8"?><m2m:rqp xmlns:m2m="http://www.onem2m.org/xml/protocols"><op>2</op><to>/[0]/MNCSE-node/deviceInfo</to> <fr>/Openhab</fr> <rqi>0002bf63</rqi></m2m:rqp>"` works. If you have time you could try some variations (of the url) of these until you get a response. Anything other than a 404 is a win :)
